TARGET  := ../bin/marketprice/marketprice
INCS = -I ../network -I ../utils
LIBS = -L ../utils -lutils -L ../network -lnetwork  -lev -ljansson -lmpdec -lrdkafka -lz -llz4  -L /usr/local/opt/openssl/lib -lssl -lcrypto -lhiredis  -lm -lpthread -ldl -lcurl -lstdc++
include ../makefile.inc
