TARGET  := marketprice.exe
INCS = -I ../../network -I ../../utils
LIBS = -L ../../utils -lutils -L ../../network -lnetwork  -lev -ljansson -lmpdec -lrdkafka -lz -L  /usr/local/opt/openssl/lib  -lssl -lcrypto -lhiredis  -lm -lpthread -ldl
include ../../makefile.inc
