TARGET  := ../bin/alertcenter/alertcenter
INCS = -I ../network -I ../utils
LIBS = -L ../utils -lutils -L ../network -lnetwork  -lev -lhiredis -ljansson -lmpdec -lcurl -L  /usr/local/opt/openssl/lib  -lssl -lcrypto  -lm
include ../makefile.inc
