TARGET  := ../bin/matchengine/matchengine
INCS = -I ../network -I ../utils
LIBS = -L ../utils -lutils -L ../network -lnetwork  -lev -ljansson -lmpdec -lmysqlclient -lz -lrdkafka -L /usr/local/opt/openssl/lib -lssl -lcrypto -lhiredis  -lm -lpthread -ldl
include ../makefile.inc
