TARGET  := ../bin/readhistory/readhistory
INCS = -I ../network -I ../utils
LIBS = -L ../utils -lutils -L ../network -lnetwork  -lev -ljansson -lmpdec -lmysqlclient -lz -lhiredis -lm -lpthread -ldl
include ../makefile.inc
